# Generated by Django 4.0.5 on 2022-06-21 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import time
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.FloatField(default=time.time)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('wallet_address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BuyHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_history_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.FloatField(default=time.time)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('amount_bnb', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=1024, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnb_kingdom_api.user')),
            ],
        ),
    ]
