# Generated by Django 4.0.5 on 2022-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb_kingdom_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
