# Generated by Django 4.0.5 on 2022-06-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb_kingdom_api', '0004_alter_buyhistory_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
