# Generated by Django 4.2 on 2023-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb_kingdom_api', '0005_alter_buyhistory_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=1024, null=True)),
                ('amount', models.FloatField(default=0)),
                ('pack', models.CharField(default='GOLD', max_length=1024)),
            ],
        ),
    ]
